if: branch = main
language: java
addons:
  ssh_known_hosts: 207.154.197.222
jdk: openjdk15
sudo: false
script: mvn test
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: main
before_install:
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa