if: branch = main
language: java
jdk: openjdk15
sudo: false # faster builds
script: "mvn test"
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on:
    jdk: openjdk15
  app:
    main: car-renting-service
